// Code generated by protoc-gen-go. DO NOT EDIT.
// source: employee.proto

package employeepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateEmployeeReq struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateEmployeeReq) Reset()         { *m = CreateEmployeeReq{} }
func (m *CreateEmployeeReq) String() string { return proto.CompactTextString(m) }
func (*CreateEmployeeReq) ProtoMessage()    {}
func (*CreateEmployeeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{0}
}

func (m *CreateEmployeeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmployeeReq.Unmarshal(m, b)
}
func (m *CreateEmployeeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmployeeReq.Marshal(b, m, deterministic)
}
func (m *CreateEmployeeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmployeeReq.Merge(m, src)
}
func (m *CreateEmployeeReq) XXX_Size() int {
	return xxx_messageInfo_CreateEmployeeReq.Size(m)
}
func (m *CreateEmployeeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmployeeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmployeeReq proto.InternalMessageInfo

func (m *CreateEmployeeReq) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type CreateEmployeeRes struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateEmployeeRes) Reset()         { *m = CreateEmployeeRes{} }
func (m *CreateEmployeeRes) String() string { return proto.CompactTextString(m) }
func (*CreateEmployeeRes) ProtoMessage()    {}
func (*CreateEmployeeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{1}
}

func (m *CreateEmployeeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmployeeRes.Unmarshal(m, b)
}
func (m *CreateEmployeeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmployeeRes.Marshal(b, m, deterministic)
}
func (m *CreateEmployeeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmployeeRes.Merge(m, src)
}
func (m *CreateEmployeeRes) XXX_Size() int {
	return xxx_messageInfo_CreateEmployeeRes.Size(m)
}
func (m *CreateEmployeeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmployeeRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmployeeRes proto.InternalMessageInfo

func (m *CreateEmployeeRes) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type ReadEmployeeReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadEmployeeReq) Reset()         { *m = ReadEmployeeReq{} }
func (m *ReadEmployeeReq) String() string { return proto.CompactTextString(m) }
func (*ReadEmployeeReq) ProtoMessage()    {}
func (*ReadEmployeeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{2}
}

func (m *ReadEmployeeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadEmployeeReq.Unmarshal(m, b)
}
func (m *ReadEmployeeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadEmployeeReq.Marshal(b, m, deterministic)
}
func (m *ReadEmployeeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadEmployeeReq.Merge(m, src)
}
func (m *ReadEmployeeReq) XXX_Size() int {
	return xxx_messageInfo_ReadEmployeeReq.Size(m)
}
func (m *ReadEmployeeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadEmployeeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadEmployeeReq proto.InternalMessageInfo

func (m *ReadEmployeeReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadEmployeeRes struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadEmployeeRes) Reset()         { *m = ReadEmployeeRes{} }
func (m *ReadEmployeeRes) String() string { return proto.CompactTextString(m) }
func (*ReadEmployeeRes) ProtoMessage()    {}
func (*ReadEmployeeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{3}
}

func (m *ReadEmployeeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadEmployeeRes.Unmarshal(m, b)
}
func (m *ReadEmployeeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadEmployeeRes.Marshal(b, m, deterministic)
}
func (m *ReadEmployeeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadEmployeeRes.Merge(m, src)
}
func (m *ReadEmployeeRes) XXX_Size() int {
	return xxx_messageInfo_ReadEmployeeRes.Size(m)
}
func (m *ReadEmployeeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadEmployeeRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadEmployeeRes proto.InternalMessageInfo

func (m *ReadEmployeeRes) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type UpdateEmployeeReq struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateEmployeeReq) Reset()         { *m = UpdateEmployeeReq{} }
func (m *UpdateEmployeeReq) String() string { return proto.CompactTextString(m) }
func (*UpdateEmployeeReq) ProtoMessage()    {}
func (*UpdateEmployeeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{4}
}

func (m *UpdateEmployeeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmployeeReq.Unmarshal(m, b)
}
func (m *UpdateEmployeeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmployeeReq.Marshal(b, m, deterministic)
}
func (m *UpdateEmployeeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmployeeReq.Merge(m, src)
}
func (m *UpdateEmployeeReq) XXX_Size() int {
	return xxx_messageInfo_UpdateEmployeeReq.Size(m)
}
func (m *UpdateEmployeeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmployeeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmployeeReq proto.InternalMessageInfo

func (m *UpdateEmployeeReq) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type UpdateEmployeeRes struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateEmployeeRes) Reset()         { *m = UpdateEmployeeRes{} }
func (m *UpdateEmployeeRes) String() string { return proto.CompactTextString(m) }
func (*UpdateEmployeeRes) ProtoMessage()    {}
func (*UpdateEmployeeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{5}
}

func (m *UpdateEmployeeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmployeeRes.Unmarshal(m, b)
}
func (m *UpdateEmployeeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmployeeRes.Marshal(b, m, deterministic)
}
func (m *UpdateEmployeeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmployeeRes.Merge(m, src)
}
func (m *UpdateEmployeeRes) XXX_Size() int {
	return xxx_messageInfo_UpdateEmployeeRes.Size(m)
}
func (m *UpdateEmployeeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmployeeRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmployeeRes proto.InternalMessageInfo

func (m *UpdateEmployeeRes) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type DeleteEmployeeReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEmployeeReq) Reset()         { *m = DeleteEmployeeReq{} }
func (m *DeleteEmployeeReq) String() string { return proto.CompactTextString(m) }
func (*DeleteEmployeeReq) ProtoMessage()    {}
func (*DeleteEmployeeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{6}
}

func (m *DeleteEmployeeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEmployeeReq.Unmarshal(m, b)
}
func (m *DeleteEmployeeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEmployeeReq.Marshal(b, m, deterministic)
}
func (m *DeleteEmployeeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEmployeeReq.Merge(m, src)
}
func (m *DeleteEmployeeReq) XXX_Size() int {
	return xxx_messageInfo_DeleteEmployeeReq.Size(m)
}
func (m *DeleteEmployeeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEmployeeReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEmployeeReq proto.InternalMessageInfo

func (m *DeleteEmployeeReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteEmployeeRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEmployeeRes) Reset()         { *m = DeleteEmployeeRes{} }
func (m *DeleteEmployeeRes) String() string { return proto.CompactTextString(m) }
func (*DeleteEmployeeRes) ProtoMessage()    {}
func (*DeleteEmployeeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{7}
}

func (m *DeleteEmployeeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEmployeeRes.Unmarshal(m, b)
}
func (m *DeleteEmployeeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEmployeeRes.Marshal(b, m, deterministic)
}
func (m *DeleteEmployeeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEmployeeRes.Merge(m, src)
}
func (m *DeleteEmployeeRes) XXX_Size() int {
	return xxx_messageInfo_DeleteEmployeeRes.Size(m)
}
func (m *DeleteEmployeeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEmployeeRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEmployeeRes proto.InternalMessageInfo

func (m *DeleteEmployeeRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListEmployeeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEmployeeReq) Reset()         { *m = ListEmployeeReq{} }
func (m *ListEmployeeReq) String() string { return proto.CompactTextString(m) }
func (*ListEmployeeReq) ProtoMessage()    {}
func (*ListEmployeeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{8}
}

func (m *ListEmployeeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEmployeeReq.Unmarshal(m, b)
}
func (m *ListEmployeeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEmployeeReq.Marshal(b, m, deterministic)
}
func (m *ListEmployeeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEmployeeReq.Merge(m, src)
}
func (m *ListEmployeeReq) XXX_Size() int {
	return xxx_messageInfo_ListEmployeeReq.Size(m)
}
func (m *ListEmployeeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEmployeeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListEmployeeReq proto.InternalMessageInfo

type ListEmployeeRes struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListEmployeeRes) Reset()         { *m = ListEmployeeRes{} }
func (m *ListEmployeeRes) String() string { return proto.CompactTextString(m) }
func (*ListEmployeeRes) ProtoMessage()    {}
func (*ListEmployeeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{9}
}

func (m *ListEmployeeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEmployeeRes.Unmarshal(m, b)
}
func (m *ListEmployeeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEmployeeRes.Marshal(b, m, deterministic)
}
func (m *ListEmployeeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEmployeeRes.Merge(m, src)
}
func (m *ListEmployeeRes) XXX_Size() int {
	return xxx_messageInfo_ListEmployeeRes.Size(m)
}
func (m *ListEmployeeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEmployeeRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListEmployeeRes proto.InternalMessageInfo

func (m *ListEmployeeRes) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type Employee struct {
	EId                  string   `protobuf:"bytes,1,opt,name=e_id,json=eId,proto3" json:"e_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lname                string   `protobuf:"bytes,3,opt,name=lname,proto3" json:"lname,omitempty"`
	IdU                  string   `protobuf:"bytes,4,opt,name=id_u,json=idU,proto3" json:"id_u,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{10}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetEId() string {
	if m != nil {
		return m.EId
	}
	return ""
}

func (m *Employee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Employee) GetLname() string {
	if m != nil {
		return m.Lname
	}
	return ""
}

func (m *Employee) GetIdU() string {
	if m != nil {
		return m.IdU
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateEmployeeReq)(nil), "service.CreateEmployeeReq")
	proto.RegisterType((*CreateEmployeeRes)(nil), "service.CreateEmployeeRes")
	proto.RegisterType((*ReadEmployeeReq)(nil), "service.ReadEmployeeReq")
	proto.RegisterType((*ReadEmployeeRes)(nil), "service.ReadEmployeeRes")
	proto.RegisterType((*UpdateEmployeeReq)(nil), "service.UpdateEmployeeReq")
	proto.RegisterType((*UpdateEmployeeRes)(nil), "service.UpdateEmployeeRes")
	proto.RegisterType((*DeleteEmployeeReq)(nil), "service.DeleteEmployeeReq")
	proto.RegisterType((*DeleteEmployeeRes)(nil), "service.DeleteEmployeeRes")
	proto.RegisterType((*ListEmployeeReq)(nil), "service.ListEmployeeReq")
	proto.RegisterType((*ListEmployeeRes)(nil), "service.ListEmployeeRes")
	proto.RegisterType((*Employee)(nil), "service.Employee")
}

func init() { proto.RegisterFile("employee.proto", fileDescriptor_eb50a19aa79a6eac) }

var fileDescriptor_eb50a19aa79a6eac = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xb1, 0x4e, 0xe3, 0x40,
	0x10, 0x86, 0x65, 0x27, 0x77, 0xc9, 0xcd, 0xe5, 0x6c, 0x79, 0x75, 0xa7, 0xb3, 0x56, 0x14, 0x60,
	0x1a, 0x14, 0x29, 0x31, 0x0a, 0x1d, 0x15, 0x0a, 0x50, 0x20, 0x51, 0x19, 0xa5, 0x20, 0x14, 0x91,
	0x93, 0x1d, 0x45, 0x2b, 0x39, 0xb6, 0xc9, 0x3a, 0x48, 0x08, 0xd1, 0xf0, 0x0a, 0x3c, 0x1a, 0xaf,
	0x40, 0xcd, 0x33, 0xa0, 0xac, 0x63, 0xb3, 0xb6, 0x71, 0x11, 0xe8, 0x32, 0x33, 0xff, 0xfc, 0xf9,
	0x66, 0xf5, 0xcb, 0x60, 0xe0, 0x22, 0x0e, 0xa2, 0x7b, 0xc4, 0x7e, 0xbc, 0x8c, 0x92, 0x88, 0xb4,
	0x04, 0x2e, 0xef, 0xf8, 0x0c, 0xe9, 0xce, 0x3c, 0x8a, 0xe6, 0x01, 0xba, 0x7e, 0xcc, 0x5d, 0x3f,
	0x0c, 0xa3, 0xc4, 0x4f, 0x78, 0x14, 0x8a, 0x54, 0xe6, 0x0c, 0xc1, 0x3a, 0x5d, 0xa2, 0x9f, 0xe0,
	0xf9, 0x66, 0xdd, 0xc3, 0x5b, 0xd2, 0x83, 0x76, 0xe6, 0x66, 0x6b, 0xbb, 0xda, 0xc1, 0xef, 0x81,
	0xd5, 0xdf, 0xd8, 0xf5, 0x73, 0x5d, 0x2e, 0xf9, 0xcc, 0x43, 0x6c, 0xeb, 0xb1, 0x07, 0xa6, 0x87,
	0x3e, 0x53, 0x29, 0x0c, 0xd0, 0x39, 0x93, 0xbb, 0xbf, 0x3c, 0x9d, 0x33, 0xe7, 0xa4, 0x2c, 0x11,
	0x5f, 0x00, 0x1d, 0xc5, 0xec, 0xdb, 0xc7, 0x96, 0x3d, 0xb6, 0xe6, 0xd8, 0x07, 0xeb, 0x0c, 0x03,
	0x2c, 0x72, 0x94, 0xcf, 0xed, 0x55, 0x45, 0x82, 0xd8, 0xd0, 0x12, 0xab, 0xd9, 0x0c, 0x85, 0x90,
	0xca, 0xb6, 0x97, 0x95, 0x8e, 0x05, 0xe6, 0x25, 0x17, 0x89, 0xe2, 0xb8, 0x7e, 0xb0, 0x62, 0x6b,
	0x6b, 0xd0, 0x31, 0xb4, 0xb3, 0x2e, 0xb1, 0xa0, 0x89, 0x93, 0x9c, 0xb0, 0x81, 0x17, 0x8c, 0x10,
	0x68, 0x86, 0xfe, 0x02, 0x6d, 0x5d, 0xb6, 0xe4, 0x6f, 0xf2, 0x17, 0x7e, 0x04, 0xb2, 0xd9, 0x90,
	0xcd, 0xb4, 0x58, 0x2f, 0x73, 0x36, 0x59, 0xd9, 0xcd, 0x74, 0x99, 0xb3, 0xd1, 0xe0, 0xad, 0x01,
	0x66, 0x66, 0x7e, 0x95, 0x22, 0x90, 0x09, 0x18, 0xc5, 0x24, 0x11, 0x9a, 0xe3, 0x55, 0x62, 0x4a,
	0xeb, 0x67, 0xc2, 0xf9, 0xf7, 0xf4, 0xf2, 0xfa, 0xac, 0x9b, 0x0e, 0xb8, 0xd9, 0x31, 0xe2, 0x58,
	0xeb, 0x92, 0x1b, 0xe8, 0xa8, 0x19, 0x22, 0x76, 0x6e, 0x51, 0x4a, 0x1f, 0xad, 0x9b, 0x08, 0xe7,
	0xbf, 0xb4, 0xb6, 0x88, 0xf9, 0x61, 0xed, 0x3e, 0x70, 0xf6, 0xb8, 0xa6, 0x2f, 0x46, 0x43, 0xa1,
	0xaf, 0xe4, 0x8e, 0xd6, 0xcf, 0x72, 0x7a, 0x5a, 0xa2, 0xf7, 0xc1, 0x28, 0x46, 0x42, 0xf9, 0x83,
	0x4a, 0xa0, 0x68, 0xfd, 0x2c, 0xbf, 0xa1, 0x5b, 0xb9, 0xe1, 0x1a, 0xfe, 0xa8, 0x99, 0x11, 0xca,
	0x0b, 0x95, 0xe2, 0x45, 0xeb, 0x26, 0xc2, 0x21, 0xd2, 0xbd, 0x43, 0x14, 0xfc, 0x43, 0x6d, 0xd8,
	0x19, 0x43, 0x56, 0xc6, 0xd3, 0xe9, 0x4f, 0xf9, 0xfd, 0x39, 0x7a, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0x68, 0x9a, 0x92, 0x9d, 0xb8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	CreateEmployee(ctx context.Context, in *CreateEmployeeReq, opts ...grpc.CallOption) (*CreateEmployeeRes, error)
	ReadEmployee(ctx context.Context, in *ReadEmployeeReq, opts ...grpc.CallOption) (*ReadEmployeeRes, error)
	UpdateEmployee(ctx context.Context, in *UpdateEmployeeReq, opts ...grpc.CallOption) (*UpdateEmployeeRes, error)
	DeleteEmployee(ctx context.Context, in *DeleteEmployeeReq, opts ...grpc.CallOption) (*DeleteEmployeeRes, error)
	ListEmployees(ctx context.Context, in *ListEmployeeReq, opts ...grpc.CallOption) (EmployeeService_ListEmployeesClient, error)
}

type employeeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServiceClient(cc *grpc.ClientConn) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) CreateEmployee(ctx context.Context, in *CreateEmployeeReq, opts ...grpc.CallOption) (*CreateEmployeeRes, error) {
	out := new(CreateEmployeeRes)
	err := c.cc.Invoke(ctx, "/service.EmployeeService/CreateEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) ReadEmployee(ctx context.Context, in *ReadEmployeeReq, opts ...grpc.CallOption) (*ReadEmployeeRes, error) {
	out := new(ReadEmployeeRes)
	err := c.cc.Invoke(ctx, "/service.EmployeeService/ReadEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) UpdateEmployee(ctx context.Context, in *UpdateEmployeeReq, opts ...grpc.CallOption) (*UpdateEmployeeRes, error) {
	out := new(UpdateEmployeeRes)
	err := c.cc.Invoke(ctx, "/service.EmployeeService/UpdateEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) DeleteEmployee(ctx context.Context, in *DeleteEmployeeReq, opts ...grpc.CallOption) (*DeleteEmployeeRes, error) {
	out := new(DeleteEmployeeRes)
	err := c.cc.Invoke(ctx, "/service.EmployeeService/DeleteEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) ListEmployees(ctx context.Context, in *ListEmployeeReq, opts ...grpc.CallOption) (EmployeeService_ListEmployeesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeService_serviceDesc.Streams[0], "/service.EmployeeService/ListEmployees", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceListEmployeesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EmployeeService_ListEmployeesClient interface {
	Recv() (*ListEmployeeRes, error)
	grpc.ClientStream
}

type employeeServiceListEmployeesClient struct {
	grpc.ClientStream
}

func (x *employeeServiceListEmployeesClient) Recv() (*ListEmployeeRes, error) {
	m := new(ListEmployeeRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	CreateEmployee(context.Context, *CreateEmployeeReq) (*CreateEmployeeRes, error)
	ReadEmployee(context.Context, *ReadEmployeeReq) (*ReadEmployeeRes, error)
	UpdateEmployee(context.Context, *UpdateEmployeeReq) (*UpdateEmployeeRes, error)
	DeleteEmployee(context.Context, *DeleteEmployeeReq) (*DeleteEmployeeRes, error)
	ListEmployees(*ListEmployeeReq, EmployeeService_ListEmployeesServer) error
}

// UnimplementedEmployeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (*UnimplementedEmployeeServiceServer) CreateEmployee(ctx context.Context, req *CreateEmployeeReq) (*CreateEmployeeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmployee not implemented")
}
func (*UnimplementedEmployeeServiceServer) ReadEmployee(ctx context.Context, req *ReadEmployeeReq) (*ReadEmployeeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadEmployee not implemented")
}
func (*UnimplementedEmployeeServiceServer) UpdateEmployee(ctx context.Context, req *UpdateEmployeeReq) (*UpdateEmployeeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmployee not implemented")
}
func (*UnimplementedEmployeeServiceServer) DeleteEmployee(ctx context.Context, req *DeleteEmployeeReq) (*DeleteEmployeeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmployee not implemented")
}
func (*UnimplementedEmployeeServiceServer) ListEmployees(req *ListEmployeeReq, srv EmployeeService_ListEmployeesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEmployees not implemented")
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_CreateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmployeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).CreateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.EmployeeService/CreateEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).CreateEmployee(ctx, req.(*CreateEmployeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_ReadEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadEmployeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).ReadEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.EmployeeService/ReadEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).ReadEmployee(ctx, req.(*ReadEmployeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_UpdateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmployeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).UpdateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.EmployeeService/UpdateEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).UpdateEmployee(ctx, req.(*UpdateEmployeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_DeleteEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmployeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).DeleteEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.EmployeeService/DeleteEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).DeleteEmployee(ctx, req.(*DeleteEmployeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_ListEmployees_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEmployeeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmployeeServiceServer).ListEmployees(m, &employeeServiceListEmployeesServer{stream})
}

type EmployeeService_ListEmployeesServer interface {
	Send(*ListEmployeeRes) error
	grpc.ServerStream
}

type employeeServiceListEmployeesServer struct {
	grpc.ServerStream
}

func (x *employeeServiceListEmployeesServer) Send(m *ListEmployeeRes) error {
	return x.ServerStream.SendMsg(m)
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmployee",
			Handler:    _EmployeeService_CreateEmployee_Handler,
		},
		{
			MethodName: "ReadEmployee",
			Handler:    _EmployeeService_ReadEmployee_Handler,
		},
		{
			MethodName: "UpdateEmployee",
			Handler:    _EmployeeService_UpdateEmployee_Handler,
		},
		{
			MethodName: "DeleteEmployee",
			Handler:    _EmployeeService_DeleteEmployee_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEmployees",
			Handler:       _EmployeeService_ListEmployees_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "employee.proto",
}
